/*
 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
 \ Empresa.: Denny Paulista Azevedo Filho
 \ Programa: R00101F9.PRG
 \ Data....: 11-01-96
 \ Sistema.: Triton - Controle Imobili rio
 \ Funcao..: nome recibo do relat¢rio TRI_R001
 \ Analista: Denny Paulista Azevedo Filho
 \ Criacao.: Programado manualmente pelo analista
 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
*/

#include "triton.ch"    // inicializa constantes manifestas
Local mResp
mResp = 'Recibo de Aluguel'
RETU mResp // <- deve retornar um valor qualquer

* \\ Final de R00101F9.PRG
